version: '3.8'

services:
  web:
    build: .
    container_name: morphing-kartoffel
    restart: unless-stopped
    ports:
      - "17777:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
    command: flask run --host=0.0.0.0
